#!/bin/bash
#alias ls='ls --color=auto'
alias kc=kubectl
alias ap=ansible-playbook
alias dc=docker-compose
alias gp='git push origin $(git rev-parse --abbrev-ref HEAD); git push heroku $(git rev-parse --abbrev-ref HEAD):master'
alias rupture='ssh aharris@rupture.net'
alias vagrant='time vagrant'
alias vi='/usr/bin/vim'

export CLICOLOR=1
export PS1="\[$(tput bold)\][\[$(tput setaf 6)\]\u@\[$(tput setaf 4)\]\h:\[$(tput setaf 7)\]\W\[$(tput sgr0)\]] "
export LSCOLORS="Ea"
