---
services: docker
sudo: required
script:
  - docker build -t nginx docker/nginx
  - docker run -d --rm nginx
  - docker build -t postgres docker/postgres
  - docker run -d --rm postgres
  - docker build -t gcorp docker/gcorp
  - docker run -d --rm gcorp
after_script:
  - docker stop nginx
  - docker stop postgres
  - docker stop gcorp
...
