---
- hosts: consul
  become: "yes"
  tasks:
    - name: "unarchive consul.zip -> /usr/bin/consul"
      unarchive:
        src: http://bit.ly/2nnEJmC
        dest: /usr/bin
        copy: "no"
    - name: "chmod +x /usr/bin/consul"
      file:
        dest: /usr/bin/consul
        mode: +x
        state: file
    - name: 'service install consul'
      copy:
        src: actual.service
        dest: /lib/systemd/system/consul.service
    - name: 'service state and enable'
      service:
        state: started
        name: consul
        enabled: "yes"
...
