---
- name: "Docker and minor updates."
  hosts: all
  tasks:
    - wait_for_connection:
    - name: "Copy slightly more secure sshd."
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
    - name: "Copy bashrc."
      copy:
        src: bashrc
        dest: /home/duchess/.bashrc
    - name: "Enable Docker."
      service:
        name: docker
        state: started
        enabled: 'yes'
      become: 'yes'
    - name: "Source bashrc."
      lineinfile:
        dest: /home/duchess/.bash_profile
        state: present
        line: "source ~/.bashrc"
...
