---
- name: "Docker and minor updates."
  hosts: all
  tasks:
    - wait_for_connection:
    - copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
      become: "yes"
    - service:
        name: docker
        state: started
        enabled: 'yes'
      become: 'yes'
    - copy:
        src: bashrc
        dest: /home/duchess/.bashrc
    - lineinfile:
        dest: /home/duchess/.bash_profile
        state: present
        line: "source ~/.bashrc"
    - get_url:
        url: http://bit.ly/2DJMRrD
        dest: /tmp/terraform.zip
    - unarchive:
        src: /tmp/terraform.zip
        dest: /usr/bin
        copy: "no"
      become: "yes"
    - file:
        dest: /usr/bin/terraform
        owner: duchess
        group: docker
        mode: ug+x
        state: file
      become: "yes"
    - shell: terraform plan
      args:
        chdir: /srv/infrastructure/docker
...
