---
- name: "Install Docker and add a user."
  hosts: do
  tasks:
    - name: "Install Docker."
      pacman:
        update_cache: "yes"
        name: "docker"
        state: "present"
      tags: docker
    - name: "Create wheel."
      group:
        name: wheel
        state: present
      tags: user
    - name: "Create a user."
      user:
        name: duchess
        state: present
        groups: wheel
        home: /home/duchess
        shell: /bin/bash
      tags: user
    - name: "Allow remote login for user."
      authorized_key:
        user: duchess
        key: "{{ lookup('file', '/Users/duchess/.ssh/id_rsa.pub') }}"
        state: present
    - name: "Update sudoers."
      copy:
        src: sudoers
        dest: /etc/sudoers
...
