---
- hosts: all
  user: root
  tasks:
    - pacman:
        update_cache: "yes"
    - pacman:
        name: docker
        state: present
    - user:
        name: duchess
        state: present
        home: /home/duchess
        shell: /bin/bash
        groups: sudo
    - authorized_key:
        user: duchess
        key: "{{ lookup('file', '/Users/duchess/.ssh/id_rsa.pub') }}"
        state: present
        tag: key
    - copy:
        src: /Users/duchess/.bashrc
        dest: /home/duchess/.bashrc
...
